# Generated by Django 3.0.4 on 2020-03-11 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('semester', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='module_rating',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='module',
            name='professors',
        ),
        migrations.RemoveField(
            model_name='module',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='module',
            name='year',
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Module'),
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='professors',
            field=models.ManyToManyField(to='ratings.Professor'),
        ),
        migrations.AddField(
            model_name='rating',
            name='module_instance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ratings.ModuleInstance'),
            preserve_default=False,
        ),
    ]
