# Generated by Django 3.0.4 on 2020-03-16 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20200311_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinstance',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.Module'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='uid',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='rating',
            name='module_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.ModuleInstance'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='professor_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ratings.Professor'),
        ),
    ]
